# permissions for end users to edit pocketidinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pocketid-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocketidinstance-editor-role
rules:
- apiGroups:
  - pocketid.pocketid.tobiash.github.io
  resources:
  - pocketidinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pocketid.pocketid.tobiash.github.io
  resources:
  - pocketidinstances/status
  verbs:
  - get
