apiVersion: pocketid.pocketid.tobiash.github.io/v1alpha1
kind: PocketIDUser
metadata:
  labels:
    app.kubernetes.io/name: pocketid-operator
    app.kubernetes.io/managed-by: kustomize
  name: pocketiduser-sample
spec:
  # TODO(user): Add fields here
