apiVersion: pocketid.tobiash.github.io/v1alpha1
kind: PocketIDUser
metadata:
  name: sample-user
spec:
  instanceRef:
    name: test
  username: jdoe
  email: jdoe@example.com
  firstName: John
  lastName: Doe
  displayName: John Doe
