apiVersion: pocketid.tobiash.github.io/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: sample-oidc-client
spec:
  instanceRef:
    name: test
  name: My Web App
  callbackURLs:
    - https://myapp.example.com/callback
  logoutCallbackURLs:
    - https://myapp.example.com/logout
  credentialsSecretRef:
    name: my-app-oidc-credentials
