//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedReferences) DeepCopyInto(out *AllowedReferences) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = new(NamespacesFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedReferences.
func (in *AllowedReferences) DeepCopy() *AllowedReferences {
	if in == nil {
		return nil
	}
	out := new(AllowedReferences)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossNamespaceObjectReference) DeepCopyInto(out *CrossNamespaceObjectReference) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossNamespaceObjectReference.
func (in *CrossNamespaceObjectReference) DeepCopy() *CrossNamespaceObjectReference {
	if in == nil {
		return nil
	}
	out := new(CrossNamespaceObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomClaim) DeepCopyInto(out *CustomClaim) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomClaim.
func (in *CustomClaim) DeepCopy() *CustomClaim {
	if in == nil {
		return nil
	}
	out := new(CustomClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.PostgresSecretRef != nil {
		in, out := &in.PostgresSecretRef, &out.PostgresSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyGatewayConfig) DeepCopyInto(out *EnvoyGatewayConfig) {
	*out = *in
	if in.HTTPRouteRef != nil {
		in, out := &in.HTTPRouteRef, &out.HTTPRouteRef
		*out = new(NamespacedObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyGatewayConfig.
func (in *EnvoyGatewayConfig) DeepCopy() *EnvoyGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(EnvoyGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialAdminConfig) DeepCopyInto(out *InitialAdminConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialAdminConfig.
func (in *InitialAdminConfig) DeepCopy() *InitialAdminConfig {
	if in == nil {
		return nil
	}
	out := new(InitialAdminConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectReference) DeepCopyInto(out *NamespacedObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectReference.
func (in *NamespacedObjectReference) DeepCopy() *NamespacedObjectReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacesFrom) DeepCopyInto(out *NamespacesFrom) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(FromNamespaces)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacesFrom.
func (in *NamespacesFrom) DeepCopy() *NamespacesFrom {
	if in == nil {
		return nil
	}
	out := new(NamespacesFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCConfig) DeepCopyInto(out *PVCConfig) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCConfig.
func (in *PVCConfig) DeepCopy() *PVCConfig {
	if in == nil {
		return nil
	}
	out := new(PVCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstance) DeepCopyInto(out *PocketIDInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstance.
func (in *PocketIDInstance) DeepCopy() *PocketIDInstance {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceList) DeepCopyInto(out *PocketIDInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceList.
func (in *PocketIDInstanceList) DeepCopy() *PocketIDInstanceList {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceSpec) DeepCopyInto(out *PocketIDInstanceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.EncryptionKeySecretRef != nil {
		in, out := &in.EncryptionKeySecretRef, &out.EncryptionKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	if in.StaticAPIKeySecretRef != nil {
		in, out := &in.StaticAPIKeySecretRef, &out.StaticAPIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
	in.Database.DeepCopyInto(&out.Database)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(SMTPConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.InitialAdmin != nil {
		in, out := &in.InitialAdmin, &out.InitialAdmin
		*out = new(InitialAdminConfig)
		**out = **in
	}
	if in.AllowedReferences != nil {
		in, out := &in.AllowedReferences, &out.AllowedReferences
		*out = new(AllowedReferences)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceSpec.
func (in *PocketIDInstanceSpec) DeepCopy() *PocketIDInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDInstanceStatus) DeepCopyInto(out *PocketIDInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDInstanceStatus.
func (in *PocketIDInstanceStatus) DeepCopy() *PocketIDInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClient) DeepCopyInto(out *PocketIDOIDCClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClient.
func (in *PocketIDOIDCClient) DeepCopy() *PocketIDOIDCClient {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDOIDCClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientList) DeepCopyInto(out *PocketIDOIDCClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDOIDCClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientList.
func (in *PocketIDOIDCClientList) DeepCopy() *PocketIDOIDCClientList {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDOIDCClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientSpec) DeepCopyInto(out *PocketIDOIDCClientSpec) {
	*out = *in
	in.InstanceRef.DeepCopyInto(&out.InstanceRef)
	if in.CallbackURLs != nil {
		in, out := &in.CallbackURLs, &out.CallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogoutCallbackURLs != nil {
		in, out := &in.LogoutCallbackURLs, &out.LogoutCallbackURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedUserGroupRefs != nil {
		in, out := &in.AllowedUserGroupRefs, &out.AllowedUserGroupRefs
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.HTTPRouteSelector != nil {
		in, out := &in.HTTPRouteSelector, &out.HTTPRouteSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyGateway != nil {
		in, out := &in.EnvoyGateway, &out.EnvoyGateway
		*out = new(EnvoyGatewayConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientSpec.
func (in *PocketIDOIDCClientSpec) DeepCopy() *PocketIDOIDCClientSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDOIDCClientStatus) DeepCopyInto(out *PocketIDOIDCClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDOIDCClientStatus.
func (in *PocketIDOIDCClientStatus) DeepCopy() *PocketIDOIDCClientStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDOIDCClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUser) DeepCopyInto(out *PocketIDUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUser.
func (in *PocketIDUser) DeepCopy() *PocketIDUser {
	if in == nil {
		return nil
	}
	out := new(PocketIDUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroup) DeepCopyInto(out *PocketIDUserGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroup.
func (in *PocketIDUserGroup) DeepCopy() *PocketIDUserGroup {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupList) DeepCopyInto(out *PocketIDUserGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDUserGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupList.
func (in *PocketIDUserGroupList) DeepCopy() *PocketIDUserGroupList {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupSpec) DeepCopyInto(out *PocketIDUserGroupSpec) {
	*out = *in
	in.InstanceRef.DeepCopyInto(&out.InstanceRef)
	if in.CustomClaims != nil {
		in, out := &in.CustomClaims, &out.CustomClaims
		*out = make([]CustomClaim, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupSpec.
func (in *PocketIDUserGroupSpec) DeepCopy() *PocketIDUserGroupSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserGroupStatus) DeepCopyInto(out *PocketIDUserGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserGroupStatus.
func (in *PocketIDUserGroupStatus) DeepCopy() *PocketIDUserGroupStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserList) DeepCopyInto(out *PocketIDUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PocketIDUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserList.
func (in *PocketIDUserList) DeepCopy() *PocketIDUserList {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PocketIDUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserSpec) DeepCopyInto(out *PocketIDUserSpec) {
	*out = *in
	in.InstanceRef.DeepCopyInto(&out.InstanceRef)
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.UserGroupRefs != nil {
		in, out := &in.UserGroupRefs, &out.UserGroupRefs
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.OneTimeAccessSecretRef != nil {
		in, out := &in.OneTimeAccessSecretRef, &out.OneTimeAccessSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserSpec.
func (in *PocketIDUserSpec) DeepCopy() *PocketIDUserSpec {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PocketIDUserStatus) DeepCopyInto(out *PocketIDUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.OnboardingEmailSentAt != nil {
		in, out := &in.OnboardingEmailSentAt, &out.OnboardingEmailSentAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PocketIDUserStatus.
func (in *PocketIDUserStatus) DeepCopy() *PocketIDUserStatus {
	if in == nil {
		return nil
	}
	out := new(PocketIDUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SMTPConfig) DeepCopyInto(out *SMTPConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SMTPConfig.
func (in *SMTPConfig) DeepCopy() *SMTPConfig {
	if in == nil {
		return nil
	}
	out := new(SMTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Config)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
